apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapkotp2-deployment
spec:
  replicas: 1  # Number of NGINX pods to run
  selector:
    matchLabels:
      app: sapkotp2
  template:
    metadata:
      labels:
        app: sapkotp2
    spec:
      containers:
      - name: sapkotp2
        image: cithit/Parbati:latest   # <-------change this!
        ports:
        - containerPort: 80  # Expose NGINX on port 80      
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sapkotp2
spec:
  rules: 
  - host: 
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend: 
          service:
            name: sapkotp2-service
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sapkotp2-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: sapkotp2
